version: "3.7"

services:
  api:
    build: ./api
    image: werkstukdev5
    ports:
      - "3000:3000"

    volumes:
      - ./api/src:/usr/app/src
    depends_on:
      - pg
  pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_CONNECTION_STRING: ${PG_CONNECTION_STRING}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
